# @baseURL=http://localhost:8080/api/v1
@baseURL=https://smarthack2024-eval.cfapps.eu12.hana.ondemand.com/api/v1
@apiKey=0177d107-0160-4c76-9512-f5c8e72eee60
@sessionId=

### start session
POST {{baseURL}}/session/start
Content-Type: application/json
API-KEY: {{apiKey}}

### End session
POST {{baseURL}}/session/end
Content-Type: application/json
API-KEY: {{apiKey}}

### Play a new day
POST {{baseURL}}/play/round
Content-Type: application/json
API-KEY: {{apiKey}}
SESSION-ID: {{sessionId}}

{
  "day": 0,
  "movements": []
}
