@baseURL=http://localhost:8080/api/v1
@apiKey=7bcd6334-bc2e-4cbf-b9d4-61cb9e868869
@sessionId=f1a41728-8ee7-4c73-a80a-bc87d332dd6d

### start session
POST {{baseURL}}/session/start
Content-Type: application/json
API-KEY: {{apiKey}}

### End session
POST {{baseURL}}/session/end
Content-Type: application/json
API-KEY: {{apiKey}}

### Play a new day
POST {{baseURL}}/play/round
Content-Type: application/json
API-KEY: {{apiKey}}
SESSION-ID: {{sessionId}}

{
  "day": 0,
  "movements": []
}
