# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.penalty import Penalty

class TestPenalty(unittest.TestCase):
    """Penalty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Penalty:
        """Test Penalty
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Penalty`
        """
        model = Penalty()
        if include_optional:
            return Penalty(
                day = 56,
                type = 'INVALID_CONNECTION',
                message = '',
                cost = 1.337,
                co2 = 1.337
            )
        else:
            return Penalty(
        )
        """

    def testPenalty(self):
        """Test Penalty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
