# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.demand import Demand

class TestDemand(unittest.TestCase):
    """Demand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Demand:
        """Test Demand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Demand`
        """
        model = Demand()
        if include_optional:
            return Demand(
                customer_id = '',
                amount = 56,
                post_day = 56,
                start_day = 56,
                end_day = 56
            )
        else:
            return Demand(
        )
        """

    def testDemand(self):
        """Test Demand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
