# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.day_request import DayRequest

class TestDayRequest(unittest.TestCase):
    """DayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayRequest:
        """Test DayRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DayRequest`
        """
        model = DayRequest()
        if include_optional:
            return DayRequest(
                day = 56,
                movements = [
                    api.models.movement.Movement(
                        connection_id = '', 
                        amount = 56, )
                    ]
            )
        else:
            return DayRequest(
        )
        """

    def testDayRequest(self):
        """Test DayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
