# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.play_controller_api import PlayControllerApi


class TestPlayControllerApi(unittest.TestCase):
    """PlayControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlayControllerApi()

    def tearDown(self) -> None:
        pass

    def test_play_round(self) -> None:
        """Test case for play_round

        Play a round
        """
        pass

    def test_start_session(self) -> None:
        """Test case for start_session

        Start a new session
        """
        pass

    def test_stop_session(self) -> None:
        """Test case for stop_session

        End the current session
        """
        pass


if __name__ == '__main__':
    unittest.main()
