# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Demand(BaseModel):
    """
    The demand / order of a customer
    """ # noqa: E501
    customer_id: Optional[StrictStr] = Field(default=None, description="The ID of the customer", alias="customerId")
    amount: Optional[StrictInt] = Field(default=None, description="The amount requested")
    post_day: Optional[StrictInt] = Field(default=None, description="The day when the demand was posted", alias="postDay")
    start_day: Optional[StrictInt] = Field(default=None, description="Delivery should happen no earlier than this day", alias="startDay")
    end_day: Optional[StrictInt] = Field(default=None, description="Delivery should happen no later than this day", alias="endDay")
    __properties: ClassVar[List[str]] = ["customerId", "amount", "postDay", "startDay", "endDay"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Demand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Demand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customerId": obj.get("customerId"),
            "amount": obj.get("amount"),
            "postDay": obj.get("postDay"),
            "startDay": obj.get("startDay"),
            "endDay": obj.get("endDay")
        })
        return _obj


