# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Penalty(BaseModel):
    """
    Penalty generated as a result of running the day / round
    """ # noqa: E501
    day: Optional[StrictInt] = Field(default=None, description="The day when the penalty was issued")
    type: Optional[StrictStr] = Field(default=None, description="The type of the penalty")
    message: Optional[StrictStr] = Field(default=None, description="The message explaining the penalty")
    cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The applied cost of the penalty")
    co2: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The applied co2 of the penalty")
    __properties: ClassVar[List[str]] = ["day", "type", "message", "cost", "co2"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INVALID_CONNECTION', 'REFINERY_OVER_OUTPUT', 'STORAGE_TANK_OVER_OUTPUT', 'STORAGE_TANK_OVER_INPUT', 'CUSTOMER_OVER_INPUT', 'CONNECTION_OVER_CAPACITY', 'CUSTOMER_UNEXPECTED_DELIVERY', 'CUSTOMER_EARLY_DELIVERY', 'CUSTOMER_LATE_DELIVERY', 'REFINERY_OVERFLOW', 'STORAGE_TANK_OVERFLOW', 'REFINERY_UNDERFLOW', 'STORAGE_TANK_UNDERFLOW', 'PENDING_MOVEMENTS', 'UNMET_DEMANDS']):
            raise ValueError("must be one of enum values ('INVALID_CONNECTION', 'REFINERY_OVER_OUTPUT', 'STORAGE_TANK_OVER_OUTPUT', 'STORAGE_TANK_OVER_INPUT', 'CUSTOMER_OVER_INPUT', 'CONNECTION_OVER_CAPACITY', 'CUSTOMER_UNEXPECTED_DELIVERY', 'CUSTOMER_EARLY_DELIVERY', 'CUSTOMER_LATE_DELIVERY', 'REFINERY_OVERFLOW', 'STORAGE_TANK_OVERFLOW', 'REFINERY_UNDERFLOW', 'STORAGE_TANK_UNDERFLOW', 'PENDING_MOVEMENTS', 'UNMET_DEMANDS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Penalty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Penalty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "day": obj.get("day"),
            "type": obj.get("type"),
            "message": obj.get("message"),
            "cost": obj.get("cost"),
            "co2": obj.get("co2")
        })
        return _obj


